version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: test-digital-fortress-app
    working_dir: /app
    tty: true
    ports: 
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_DATABASE: Test_Digital_Fortress
      DB_USERNAME: root
      DB_PASSWORD: root
    networks: 
      - test-digital-fortress
    depends_on: 
      - database
  database:
    image: 'mysql:8.0'
    container_name: test-digital-fortress-db
    restart: always
    volumes:
      - ./Test_Digital_Fortress.sql:/docker-entrypoint-initdb.d/Test_Digital_Fortress.sql
    environment:
      MYSQL_DATABASE: Test_Digital_Fortress
      MYSQL_ROOT_PASSWORD: root
    networks: 
      - test-digital-fortress

networks:
  test-digital-fortress:
    driver: bridge
